### PR TITLE
Update to meteor 1.3.2.4

### PR DESCRIPTION
**Pull request by jessedvrs**
No issues according to update so far. @peterpeerdeman will run a quick regression test for us.

With this update, we can:
- Use ES2015+ throughout the code (server as well as client)
- Use ES6 modules (`import` and `export`) in combination with the `/imports` directory
- Use the npm cli with `meteor npm <args>` instead of meteorhacks npm-containers
- Enjoy faster development build time

### CODE REVIEW

**Comment by jessedvrs** [comment]
I'm hyped 💩

**Comment by tlimpanont** [comment]
Read this: 

```Note: Due to same changes between Meteor 1.3.0-1.3.1 and Meteor 1.3.2+, Users of Meteor 1.3.0 or 1.3.1 are advised to use version 3.4.2 of fourseven:scss```

from https://github.com/fourseven/meteor-scss#meteor-12

I will try to also update the **fourseven:scss** and check it out

**Comment by jessedvrs** [comment]
I've tried multiple times, but the newer version lacks support of the .sass indented syntax and is generally less stable.

**Comment by tlimpanont** [comment]
Ah i see. Let's postpone that for now. Thanks for the update

**Comment by tlimpanont** [comment]
By the way, sass and scss it's very similar right? So the migration of sass to scss it's doable right? 

it's just this syntax I felt in love with. I think this is default support by 1.3.2.*
``` @import "{my-package:pretty-buttons}/buttons/_styles.scss"; ```

**Comment by jessedvrs** [comment]
Yes its absolutely doable. Its basically just accolades and semicolons. But I encountered more problems than that but I'll be pleased if you could take it a try as well.

**Pull request merged**
