### PR TITLE
fix(comments): Made the comment form id reactive so it refreshes the …

### LINKED ISSUE #236: Comments posted to different message than commented on
This is a weird one. When I sometimes post a comment on update/detail, it sometimes doesn't show as comment on the message. So I rewrite the comment and post again and it does show on the message. However, after I view the updates I see the comment I posted first appear as a comment on a different message than the one I posted it to.

Issue seen on Chrome by several users. See these screenshots for the results (comment by me accentuated).

screen shot 2016-02-04 at 11 29 40
screen shot 2016-02-04 at 11 29 56

### PR DESCRIPTION
**Pull request by andreleon**
…form when the view is switched

This pull-request fixes #236

### CODE REVIEW

**Comment by ralphboeije** [comment]
important to have this in this weeks release @tlimpanont next to the other PR's you already merged, this is a show stopping bug fix.

**Comment by tlimpanont** [comment]
@andreleon still have problem with this

something to do with the specific partup.

screen shot 2016-02-10 at 22 59 28

**Comment by peterpeerdeman** [comment]
hello @tlimpanont and @ralphboeije. I've retested this fix and it fixes the problem posting the message to the wrong update. The issue @tlimpanont is describing here is not occurring in my test setup with production data and probably has to do with the development environment fixture data. Let's discuss that problem in the issue you created for it.

**Comment by tlimpanont** [comment]
@peterpeerdeman let's update the local fixture data with a better data then. (latest acceptance for example)

**Pull request closed without merging**
