### PR TITLE
Ft meteor 1 5 upgrade

### PR DESCRIPTION
**Pull request by andreleon**
Upgrade to meteor 1.5

### CODE REVIEW

**Comment by noelheesen** [comment]
I can take a look this evening

**Comment by ralphboeije** [comment]
Findings:

- [ ] Tribe homepage, e.g.https://ft-meteor-1-5-upgrade.staging.part-up.com/tribes/lifely-open?show=true --> most active part-ups are not showing

**Comment by andreleon** [comment]
@ralphboeije 

>Tribe homepage, e.g.https://ft-meteor-1-5-upgrade.staging.part-up.com/tribes/lifely-open?show=true --> most active part-ups are not showing
This is because the cron hasnt run yet.

> Toggle notifications in user settings not possible for "when you're invited to a part-up". Error messages says "invalid_subscription" https://ft-meteor-1-5-upgrade.staging.part-up.com/profile/q63Kii9wwJX3Q6rHS/settings/notifications. Also for "when a user wants to become a partner in a part-up" notification (just saw that this only holds true for users from fixtures and not for new users, however on master.staging.part-up.com this is not an existing issue).

it is an existing issue on https://fix-tribe-settings-error-messages.staging.part-up.com

**Comment by noelheesen** [comment]
Which part's of the platform still need testing?

**Comment by ralphboeije** [comment]
I couldn't properly test win10 + IE because of a failing VM today @noelheesen If you could?

**Comment by wouterd** [comment]
I see there is an ecmascript runtime now. does that mean we can remove babel?

**Pull request merged**
