### PR TITLE
WIP: Activity re-design

### PR DESCRIPTION
**Pull request by noelheesen**
The activity re-[design](https://drive.google.com/drive/folders/0Byie6itUWBvIVmoxdTRQb0k3STQ). Not every feature was included in the design so I had to make some decisions myself. Please suggest any improvements to the design!

todos:
- [x] I want to do this icon
- [x] translations dropdown
- [x] display user info on hover contributor icon?

This PR touches the following:
- create & edit an activity;
  - edit activity now opens a popup similar to create an activity;
- add & remove files to an activity;
- archive & unarchive an activity;
- delete an activity;
- create & edit contributions;

board view & timeline:
  - show icon for files only when a file is attached to the activity;
  - only show the end date if present;
  - not show icons for contributing, these are moved to the drop-down instead;
  - show contributor icons

detail:
  - show full contributions;
  - show icons (& text) for contributing;
  - comment to activity

Closes: #1120 #339 #875 #1072 #878 #24

### CODE REVIEW

**Comment by ralphboeije** [comment]
Test findings:
- Can't add a comment to an activity from activity detail and/or updates timeline (on hover comment link missing and not activated either when clicking on hover comment link on contribution detail)
- Edit contribution: on hover there is a pencil showing on the contributor image and you can click the contribution detail (hrs
- After adding a .ai (adobe illustrator) file, there is no thumbnail (catch-all needed on file icon thumbnail?)
- Add activity can be clicked multiple times (spinner missing)

**Comment by noelheesen** [comment]
Autofocus comment only on activity detail

**Comment by noelheesen** [comment]
Idea for add/remove file from update, check in method and emit message.

**Comment by noelheesen** [comment]
@ralphboeije It's building on staging now. There's still work to be done though.

- [ ] Edit activity buy, always opens with last activity in array;
- [ ] Board subscription required for lane tags, need to optimize;

**Comment by ralphboeije** [comment]
New findings (issues visible on https://feat-activity-modal.staging.part-up.com/partups/part-up-developement-vGaxNojSerdizDPjd/activities):
- [ ] spacing card with title only: increase margin below title
- [ ] alignment file icon when no date: increase left margin
- [ ] merge master for drag-n-drop chrome bug fix
- [ ] add contribution is not visible anymore in dropdown as list item
- [ ] Erik mentioned that we really need an icon+copy to add contribution next to the invite someone option (so not just in dropdown)

https://feat-activity-modal.staging.part-up.com/partups/part-up-developement-vGaxNojSerdizDPjd/updates/d4NMYtdf5kb7s7Cu6?fe=false

**Comment by ralphboeije** [comment]
Moblie findings:
- [ ]  title on activity detail cut-off needed, as it now runs behind the dropdown icon (...)
- [ ] update title not well aligned with update timestamp (spacing and vertical position)
- [ ] on activity detail hide copy "comments" and "file" to keep that row on one line
- [ ] new activity modal: increase spacing below add activity button (same for edit activity modal of course)
- [ ] contribution edit mode: fields run over right border of activity detail

**Comment by noelheesen** [comment]
When creating a part-up you can't add new activities;

Als er comments zijn dan wel input field, anders niet.
Bij andere updates altijd xcomments + comment buttons vanuit comments laten zien;
Comment rechts boven updates weg halen

**Comment by ralphboeije** [comment]
- [ ] archived state has to have a grey, is now black
- [ ] deleted state has to have strike through title
- [ ] clicking delete on edit modal doesn't close the modal

**Comment by ralphboeije** [comment]
Latest issues found:

Edge:
* date picker doesn't expand
* card on board: click on file expands files on card instead of link to detail

General
* show system messages just on activity detail, not on conversations/all updates timeline
* Add comment on updates: new comment not displayed (chrome/edge don't work, safari works)
* created part-up update (and possibly others as well): spacing needed between update title and box with 0 comments / add comment
* Contribution update still has comment on right top corner instead of below update content (0 comments / add comment). Possibly has to do with comments belonging to activity? Low priority.
* in create flow, dropdown is gone from newly created activities (should only be removed for the dummy)
* In create flow, click on activity title should not be possible as it breaks the create flow
* Clicking Do this in dropdown doesn’t close the dropdown
* On activity detail: comments should be expanded with autofocus

safari:
* like in chrome: drag and drop has a larger area that the card that is dragged

**Comment by noelheesen** [comment]
@ralphboeije 
"Add comment on updates: new comment not displayed" Could you elaborate? I can't reproduce this as comments are always displayed when I add them.

I realize that when you copy an activity with files attached when creating a new partup, we need to re-upload the file with a new ID so that if you remove the file it won't remove it for both activities. The other option is to not include files when copying activities.

**Comment by ralphboeije** [comment]
Exactly as it says. Reproducable on chrome at least. Safari works fine. haven't tested FF.

**Comment by noelheesen** [comment]
@ralphboeije After 3+ hours and a few bold spots later I have found the cause why messages are not updated after inserting / deleting. It's a side effect from the optimization round we performed earlier. To be more precice, we cached the update in memory which caused it not to be updated as it was already there.

I have pushed fixes. I'll test on staging for a bit and then call it a day.

**Pull request merged**
