### PR TITLE
#1053 update about page image

### PR DESCRIPTION
**Pull request by FreddyAprilliant**
#1053

### CODE REVIEW

**Comment by ralphboeije** [comment]
@wouterd is this ok, or do we better have the image in S3?

**Comment by ralphboeije** [comment]
@FreddyAprilliant Thanks for your contribution! I just added the image to s3, so the code will work. However, now also the NL version of the about page has the EN version of the image. We can make it work if you add a new i18n translation key to https://github.com/part-up/part-up/blob/master/app/i18n/phraseapp.en.i18n.json and https://github.com/part-up/part-up/blob/master/app/i18n/phraseapp.nl.i18n.jsonwith the correct url's for both images.

**Comment by FreddyAprilliant** [comment]
@ralphboeije thanks for your review, i've just added the image (or should i say "we") to the NL version of the about page. Please, do double check on. about the old images in my early PR, should i erase 'em or not?

**Comment by ralphboeije** [comment]
HI @FreddyAprilliant sorry for the delay. If you can erase them indeed I will merge this one right away.

**Comment by FreddyAprilliant** [comment]
HI @ralphboeije i've deleted the old image from my previous PR, please check them again and thanks for your help.

**Comment by ralphboeije** [comment]
Thanks a lot @FreddyAprilliant small change, but it makes for another issue to be closed!

**Pull request merged**
