### PR TITLE
feat(activities): Add my activities overview

### PR DESCRIPTION
**Pull request by noelheesen**
Translation files are updated, merge into PhraseApp after closing this PR.

Closes: #1744

### CODE REVIEW

**Comment by ralphboeije** [comment]
Findings:
- Page title is still missing
- when there are >2 contributors, their profile images run over the menu (three dots)
- "I want to do it" is removed from Create Activity modal
- Question: what is the ordering of the activities without a date? I would be great if they would be clustered by part-up (title)
- Placeholder copy empty state: "You have finished all your work. Find more activities to contribute to in the Tribes and part-ups you can browse on the discover page."

**Comment by valery78** [comment]
Findings:

- date range this week. 'This week' is measured 7 days from current date. As a user I see a week as a working week, counting monday through sunday.
- edit activity option is missing for a user after accepting an invite.

**Comment by noelheesen** [comment]
@ralphboeije Case:

1. Judy is not a partner in partup;
2. John invites Judy to contribute to an activity in partup;
3. Judy wants to do it and gives a motivation;
4. The activity appears in the overview of Judy;
5. Judy can't edit the activity because the contribution is not yet verified.

Should this activity be in the activity overview of Judy?

**Comment by noelheesen** [comment]
The branch has now been successfully rebuilt.

**Pull request merged**
