### PR TITLE
Enabling emoji for updates

### PR DESCRIPTION
**Pull request by jplattel**
Emojis are now supported for updates within a partup. We might want to
change this into a template settings, but this is a start :)

### CODE REVIEW

**Comment by tlimpanont** [comment]
@jplattel Nice feat! You're right, the changes only reflect when you add a new message on the part-up page (there are a lot more places that need the support of emoji). We also want to make sure if this library match our security requirements. I think this should not be a problem since emojies are like ASCII characters. @peterpeerdeman can you confirm this? The lib is https://github.com/lookback/meteor-emoji/

**Comment by jplattel** [comment]
@tlimpanont thanks! The emoji lib can use images and unicode, and I think it's possible to use only unicode... 

As for the usability, I've made it into a function for the client, so you can re-use it for other places you might want have emoji.

**Comment by peterpeerdeman** [comment]
Hi @jplattel, I took a look at the pull request and the package that is being included. I'm a bit concerned about the Meteor.startup subscriptions, which means that each user that hits the site will open a reactive subscription to the server and loading all emojis (this also includes people loading just the homescreen and leaving). I'd prefer looking for a solution that does not require serverside interaction, e.g. regexing emoji lines ":emoji" and replacing them with a unicode character in html, the same way we replace urls with links in the "autolinker" for example. Could you give that a try?

**Comment by jplattel** [comment]
@peterpeerdeman, agreed! Will look into it! :)

**Comment by jplattel** [comment]
@peterpeerdeman I've changed things around and removed the previously used library, right now I'm using js-emoji: https://github.com/iamcal/js-emoji/blob/master/build/emoji.js.template 

It should be noted I've only tested this on OS X with native emoji... I'm not sure how this works out on Linux or Windows...

**Comment by peterpeerdeman** [comment]
rebased, reviewed and tested the branch in chrome and edge. There was some cleanup necessary from the first package and documentation was outdated, there were some jscs errors but all these findings are fixed in my latest commit. @tlimpanont it should be ready for merge now.

**Comment by ralphboeije** [comment]
Cool! We'll also have this in this release.

**Pull request merged**
