### PR TITLE
Allow CORS in HTTP calls

### PR DESCRIPTION
**Pull request by jessedvrs**
Allow CORS from all origins in HTTP calls on behalf of the [Part-up app](https://github.com/part-up/app) (subscriptions and methods already do that).

### CODE REVIEW

**Comment by wouterd** [comment]
Does the app need such a broad amount of Origins supported?
This opens up the website for a range of attacks that browsers protect against (such as cross domain javascript).

**Comment by jessedvrs** [comment]
As the hybrid app keeps his HTML/JS/CSS offline, it has to create a static web server to be able to serve those files (like every hybrid app). The origin will be something like localhost:12345 and CORS should be enabled. I don't think Part-up will be more vulnerable than it ever was since the websocket connection has CORS enabled already (by default). @peterpeerdeman ?

**Comment by jessedvrs** [comment]
Correction: it's not enabled by default in the websockets. we enabled it [in partup:server/bootstrap.js](https://github.com/part-up/part-up/blob/develop/app/packages/partup:server/bootstrap.js#L42)

**Comment by jessedvrs** [comment]
@wouterd We're going to see if we can narrow the origins by specifying `localhost`, `meteor.local`, `part-up.com`, `*.part-up.com` and `pu-*.lifely.nl`. Thanks for the critical look

**Comment by jessedvrs** [comment]
Turns out that "origin-list" in practice only allows a single origin or `null`, according to the w3 spec at https://www.w3.org/TR/cors/#access-control-allow-origin-response-header

> In practice the origin-list-or-null production is more constrained. Rather than allowing a space-separated list of origins, it is either a single origin or the string "null".

So I think we must use `*`.

**Comment by peterpeerdeman** [comment]
If we need to allow multiple hosts, we'll have to manage this header on the nginx level, either in the loadbalancer or the specific node, in a similar fashion as described [here](http://stackoverflow.com/questions/1653308/access-control-allow-origin-multiple-origin-domains). @wouterd I'm not sure how this would work in the new AWS setup though. I suggest we use the * policy for now, as @jessedvrs indicated this is already the default for the websocket connection as well.

**Comment by wouterd** [comment]
Ahh ok.. yes, I faintly remember having this discussion before with some people at ING.
Do we have enough guards in place to protect against cached credentials hijacking? If so, just use * and we'll see if we can do some things programmatically later. AWS is no problem in this, I pretty sure we're not going to use cloudfront for the meteor app.

**Comment by jessedvrs** [comment]
Meteor doesn't use cookies at all. Instead `localStorage` is used, which is much harder to spoof.

**Comment by jessedvrs** [comment]
@wouterd Could you merge this and deploy to acceptance today? The deployed part-up app relies on acceptance. If not, no problem either. 👍

**Pull request merged**
