### PR TITLE
Feat update fixtures

### PR DESCRIPTION
**Pull request by noelheesen**
The fixture data has been updated with:
- Add Boards;
- Add Lanes;
- Add Sectors;
- Add Swarm page;
- Update Tribes;
- Update Part-ups.

Now merges directly into master.

### CODE REVIEW

**Comment by jplattel** [comment]
Not merging or approving yet, Meteor throws an error:  Exception while invoking method 'activities.insert' Error: Match error: Match error: Lane id must be a valid alphanumeric ID

**Comment by noelheesen** [comment]
@peterpeerdeman @andreleon Hello, as @jplattel mentioned above meteor will throw a match error when trying to create new activities on lanes. When moving an existing activity a 'Unauthorized' error is thrown. Ralph mentioned this happened before so I was wondering if any of you know what might cause this?

**Comment by noelheesen** [comment]
@jplattel The match error should be gone now. The authorized error is still there, I've made an issue for it so we can merge this branch. Issue: #1013

**Comment by jplattel** [comment]
@noelheesen great that the match errors are fixed! Non-matching `_ids` where the problem?

**Comment by noelheesen** [comment]
@jplattel The `_ids` in general, apparently not every 17-character string with numbers and letters is accepted as alphanumeric........... :disappointed:

**Comment by jplattel** [comment]
Alphanumeric meteor IDs could be generated with the random Meteor API found here: https://docs.meteor.com/packages/random.html 

Current status of this pull request, fixed the `match failed` error, still struggling with the Unauthorised message...

**Comment by noelheesen** [comment]
@jplattel The error should be gone now! Both the User and Partup collection store the information that connects a user to a part-up, not every user had this collection so I have overlooked it.

**Pull request merged**
