### PR TITLE
feat(1-on-1-chats): active chat is on top of the chats list, also the…

### PR DESCRIPTION
**Pull request by andreleon**
This PR adds the feature that when a chat is active, it sits on top of the chats list #721

### CODE REVIEW

**Comment by ralphboeije** [comment]
@andreleon please check on https://ft-chat-active-above-fold.staging.part-up.com/ as it doesn't seem to work right

Findings:
- Chats dropdown: start a chat loads homepage, although the url changes correctly
- On refresh of page with /chats url, the loading spinner keeps showing and you can't search for a user

screen shot 2017-08-11 at 10 16 31

**Comment by andreleon** [comment]
@ralphboeije please check again, i did some fixing :)

**Comment by ralphboeije** [comment]
@andreleon looking good! Only found one issue, but that was already there I think, but might be an easy fix? User image not showing on initial load after search (see screenshots)

screen shot 2017-08-11 at 11 55 14
screen shot 2017-08-11 at 11 55 19
screen shot 2017-08-11 at 11 55 48

**Comment by andreleon** [comment]
@ralphboeije hmm this is weird, i cannot reproduce the same issues in your screenshots, dan you provide steps to reproduce?

**Comment by ralphboeije** [comment]
@andreleon Steps to reproduce (on /chats):
- Search user, click user
- type text and send message
- search another user
- click user
- see that the image is not loaded

**Comment by andreleon** [comment]
@ralphboeije sorry, i still cannot reproduce it

**Comment by ralphboeije** [comment]
@andreleon Very weird, just on my system it seems. @noelheesen also can't reproduce. And I can also reproduce on safari+mac (before on chrome+mac). I'll leave this for now then.

**Pull request merged**
