### PR TITLE
Fix new activity join partner v2

### PR DESCRIPTION
**Pull request by AnnotatedJS**
EDIT:

When a user wants to create an activity without being a partner in that part-up a redirect to a popup asking to become a partner is done.

This PR:
- Gives a warning popup with a button to request an invite to become partner when the user is not a partner and tries to create an activity;
- Opens the motivation popup when the user wants to become a partner;
- Gives a pending state when the request is sent;
- Gives messages based upon the state:
  - `pages-app-partup-activities-newactivity_restricted_paragraph`
  - `pages-app-partup-activities-newactivity_restricted_paragraph_pending` **does not yet exist**

I have moved duplicate code in a method 'isPendingPartner' on the 'User' object

@ralphboeije Could you please review / create both PhraseApp keys?

### CODE REVIEW

**Comment by AnnotatedJS** [comment]
I tried to retract my pull request without closing the branch.
This is currently not possible with GitHub.

**Comment by noelheesen** [comment]
@AnnotatedJS Could you explain why? I assume this is the right branch? I'll test it one more time and then ask ralph to merge.

**Comment by AnnotatedJS** [comment]
Because the logic is ready and tested, but the texts of the different responses are not up to standard.

**Comment by ralphboeije** [comment]
@AnnotatedJS what is the status of this PR?

**Comment by noelheesen** [comment]
@AnnotatedJS Good point. There's some work to be done textually. I want to propose the following change:
Remove the bold line on top and change the text as followed
```JS
Only partners can create new activities. Do you think an activity is missing? Just post your suggestion in a new message or send a request to become a partner.
```
Then before the request button also put in the button for a new message, we'd then have 2 buttons and the close button. @ralphboeije What do you think?

**Comment by ralphboeije** [comment]
Copy can always be changed after the PR is merged, as we do that through Phraseapp. I gave Noel some feedback wrt the design (Remove close button - add cancel option, for consistency, Improve spacing between copy and button).

**Comment by AnnotatedJS** [comment]
No problem with that but there is a third state; a user that has requested approval and his approval is pending. 
In that case the current text does not fit the situation.
1 part up incubator list

**Comment by ralphboeije** [comment]
@AnnotatedJS I will change the copy after you have completed the PR and I have merged it. There is no need to wait for copy. That can be fixed later.

**Pull request merged**
