### PR TITLE
Add linter configuration

### PR DESCRIPTION
**Pull request by noelheesen**
To improve the readability of the code this enforces strict rules about how code has to be formatted. These rules are create by airbnb and adopted by meteor and many other companies.

I have created a new script to run ESLint on any changed JS file, you can only commit when it passes.

### CODE REVIEW

**Comment by ralphboeije** [comment]
@noelheesen did you and @jplattel have a look at this one today?

**Comment by jplattel** [comment]
Yes we did! Looks good to me, the conflict with the CONTRIBUTING.md can be resolved by @noelheesen :)

**Comment by ralphboeije** [comment]
@noelheesen can you resolve this conflict?

**Comment by noelheesen** [comment]
@ralphboeije I have fixed the merge conflict. Also removed some dev-dependencies because of the new babel-runtime as discussed with @jplattel .

**Pull request merged**
