### PR TITLE
Fix email sentfrom

### PR DESCRIPTION
**Pull request by ralphboeije**
Added via Part-up to sentfrom address

### CODE REVIEW

**Comment by ralphboeije** [comment]
@noelheesen can you please review this one next week and do the same for the part-up invite and activity invite emails?

**Comment by ralphboeije** [comment]
@jplattel somehow this fix does not give the intended result. Do you have an idea why not? You can test it on beta now by sending an email invite. The sender name is visible, but the concatenation with the i18n key does not seem to work.

**Comment by jplattel** [comment]
I'll look into this today 👍

**Comment by jplattel** [comment]
Weird, when running this locally, the output from the invite is: `From: "Admin User via Part-up" <team@part-up.com>` that is correct no?

**Comment by noelheesen** [comment]
I think this might be because of `Partup.constants.EMAIL_FROM`. It get's this process variable `process.env.PARTUP_EMAIL_FROM`. We should find out what this is in prod. The thing with javascript is that you never know for sure until you find out. 

Defining the `fromAdress` before adding it might also help (highly unlikely though).
```
var fromAddress = [
    Partup.constants.EMAIL_FROM.replace(/Part-up/, inviter.profile.name),
    TAPi18n.__('emails-invite_upper_to_network-via'),
].join(' ');
```

**Pull request merged**
