### PR TITLE
Upgrade Meteor to 1.3.5.1

### PR DESCRIPTION
**Pull request by wouterd**
To prep for the 1.4 upgrade, meteor recommends to go to the latest 1.3 first, because it also supports Mongo 3.2.

@peterpeerdeman @ralphboeije can you please review / test this feature branch?

If this is good, I'd like to see if I can get this version to work on the new compose mongo offering that also allows SSL connections, which is another good security measure.
When it works on that compose version, we can proceed to 1.4.

### CODE REVIEW

**Comment by ralphboeije** [comment]
I justed tested ~75% of the features and see two issues:
- Images are not loading and it is not possible to upload pictures. This kills quite some features, like changing settings of profile/part-up/tribe
- Adding an activity will give an error, doens't close the modal and adds the activity in the background of the modal anyhow (see screenshot)

screen shot 2017-02-22 at 13 22 16

**Comment by wouterd** [comment]
Fixed the images, it was a problem with the staging environment generation script. :)

**Comment by wouterd** [comment]
As to the activity problem, from the logs:
```
Feb 22 17:45:32 meteor-1 meteor-1.stg-ft-meteor-upgrade.ee440568:  error:  Error: Board_could_not_be_found [404] 
Feb 22 17:45:32 meteor-1 meteor-1.stg-ft-meteor-upgrade.ee440568:      at [object Object].Mongo.Collection.findOneOrFail (packages/partup-server/helpers/collection.js:16:1) 
Feb 22 17:45:32 meteor-1 meteor-1.stg-ft-meteor-upgrade.ee440568:      at [object Object].Meteor.methods.activities.insert (packages/partup-server/methods/activities/activities_methods.js:28:1) 
Feb 22 17:45:32 meteor-1 meteor-1.stg-ft-meteor-upgrade.ee440568:      at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1711:12) 
Feb 22 17:45:32 meteor-1 meteor-1.stg-ft-meteor-upgrade.ee440568:      at packages/ddp-server/livedata_server.js:711:19 
Feb 22 17:45:32 meteor-1 meteor-1.stg-ft-meteor-upgrade.ee440568:      at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1) 
Feb 22 17:45:32 meteor-1 meteor-1.stg-ft-meteor-upgrade.ee440568:      at packages/ddp-server/livedata_server.js:709:40 
Feb 22 17:45:32 meteor-1 meteor-1.stg-ft-meteor-upgrade.ee440568:      at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1) 
Feb 22 17:45:32 meteor-1 meteor-1.stg-ft-meteor-upgrade.ee440568:      at packages/ddp-server/livedata_server.js:707:46 
Feb 22 17:45:32 meteor-1 meteor-1.stg-ft-meteor-upgrade.ee440568:      at tryCallTwo (/app/programs/server/npm/node_modules/meteor/promise/node_modules/promise/lib/core.js:45:5) 
Feb 22 17:45:32 meteor-1 meteor-1.stg-ft-meteor-upgrade.ee440568:      at doResolve (/app/programs/server/npm/node_modules/meteor/promise/node_modules/promise/lib/core.js:200:13) 
```

**Comment by ralphboeije** [comment]
I don't know, @prik you wrote the migrations, right? Do you know? @wouterd in that case, we can deploy it to acceptance to check this last point, otherwise we are good to go!

**Comment by prik** [comment]
The migrations run after the fixtures, so I think it has to do with the staging environment/data being altered a couple of times. I'm with @ralphboeije on this, deploy to acceptance to see if this still occurs.

**Comment by wouterd** [comment]
Ok then, here goes!

**Pull request merged**
