### PR TITLE
Sanitize unsafe HTML

### LINKED ISSUE #1235: Implement helper for allow-unsave-html
on all fields where txt is rendered as HTML

### PR DESCRIPTION
**Pull request by noelheesen**
This PR affects the following:

- latest message inside user tile in 1-on-1 chat sidebar;
- 1-on-1 chat notification;
- chat group notification;
- comments;
- search input;
- network -> settings -> about -> content-block;
- network -> settings -> homepage blocks;
- partup -> settings -> description;
- activity description (content, in all states, e.g. board/detail);
- user -> profile -> about;

closes #1235

### CODE REVIEW

**Comment by ralphboeije** [comment]
@jplattel did you already approve this one?

**Comment by jplattel** [comment]
No, looked at it, but still unsure about some things as some rendering stills seems to take place.. Will have a go/no-go this friday!

**Comment by noelheesen** [comment]
If I remember correctly the rendering happened in the part-up description. While all attributes were stripped it still rendered an  tag. @jplattel can you confirm this?

**Comment by jplattel** [comment]
Yes confirmed :)
Op za 23 sep. 2017 om 12:12 schreef Noël Heesen <notifications@github.com>

**Comment by noelheesen** [comment]
@jplattel This behavior is fixed with the latest commit. A transform function is used that sanitizes before sending it to the render template.

**Comment by ralphboeije** [comment]
Restriction levels needed:
- Standard: sanitize everything
- Markup: sanitizing scripting
 - post (markdown)
 - comment (markdown)
 - content block tribe homepage and tribe about page (wysiwyg)
- URL only
 - chat messages (1-on-1 and tribe chat)

**Pull request merged**
