### PR TITLE
fix(message): fix safari file upload

### PR DESCRIPTION
**Pull request by jessedvrs**
issue #161

### CODE REVIEW

**Comment by tlimpanont** [comment]
@jessedvrs heb niet kunnen zien werken op mijn local. Misschienkan de moxie lib safari op een van de andere manier toch niet ondersteunen. Heb jij dit ook gecheckt op IE?

**Comment by jessedvrs** [comment]
Haha, ff over op Engels... @tlimpanont is saying that the fix does't work in his Safari.
For me mOxie 'polyfill' did the trick. I'll retest this one more time. IE is working too.

**Comment by tlimpanont** [comment]
OK let me test it again! Maybe I did not have the correct ENV vars.

**Comment by tlimpanont** [comment]
@jessedvrs ./decrypt is the bitch factor for this :P

**Comment by jessedvrs** [comment]
Nice find :) :+1:

**Pull request merged**
