### PR TITLE
chore(client): Enable feature flag for BETA

### PR DESCRIPTION
**Pull request by noelheesen**
In order for this to work the .env variables need to be modified

--
`export METEOR_SETTINGS="{\"public\":{\"analyticsSettings\":{\"Google Analytics\":{\"trackingId\"\":\\"}}}}"`

++
`export METEOR_SETTINGS="{\"public\":{\"analyticsSettings\":{\"Google Analytics\":{\"trackingId\":\"\"}},\"FEATURE_FLAG\":\"1\"}}"`

closes: #1479

### CODE REVIEW

**Comment by wouterd** [comment]
1. What is this for?
2. Please do re-formats and functional changes in different commits. I can't easily see what you changed like this.

**Comment by ralphboeije** [comment]
@wouterd the case in hand is the personal homepage. It is in the code already, but the route to /home is commented out, because it is not yet finished. I would like to be able to test it on beta this week to give Leon feedback. That got us thinking if it would be possible to use a feature flag for releases, where we enable certain features only for beta, such that the team can test it in production environment and we can iterate before we set it live for all users.

**Comment by noelheesen** [comment]
@wouterd I have created 2 separate commits now.

**Comment by wouterd** [comment]
Few comments:
1. I'd like to see the feature flag used at boot-up to add the extra /home route and then at runtime it isn't needed. This removes the odd if that does a (client side) redirect when the feature flag is off which impacts performance.
1. Give the feature flag a meaningful name, something like "FEATURE_FLAG_HOME". The `>1` seems odd. Why don't you just check for truthiness?

**Comment by noelheesen** [comment]
I was thinking big and wanted to use the FEATURE_FLAG as an enumeration where features could be enabled/disabled by number.

**Comment by wouterd** [comment]
Probably easier to just make it a dict then. :)

**Pull request merged**
