### PR TITLE
Fix window title

### PR DESCRIPTION
**Pull request by avanderpluijm**
After loading the partup data, set the name of the partup in de browser window. Better for e.g. the browser's history list.

### CODE REVIEW

**Comment by ralphboeije** [comment]
As discussed with @peterpeerdeman, this should be improved before merging it to develop. The page is set rightly on visit of a part-up page, but the title is not changed after you leave this page to the next title of the page you visit.

**Comment by avanderpluijm** [comment]
Agreed, probably integrate it in the router, when possible?

**Comment by peterpeerdeman** [comment]
hi @avanderpluijm, you could try resetting the title in the Router.onBeforeAction (this runs before any route change), and maybe think about some other places where the title could be set to something more meaningful? like the tribe pages, profile pages etc.

**Comment by ralphboeije** [comment]
Hi Rene, this is also a great one to start with. Peter has already given some feedback to take it to production level, but Arn will not have time to finish this one. There are quite some users asking for this also!

**Pull request closed without merging**
