### PR TITLE
style(tooltip): Add ? explainer tooltip in create part-up form activity view 

### PR DESCRIPTION
**Pull request by nicolasmarabel**
The keys are ready, translation for nl is pending

### CODE REVIEW

**Comment by ralphboeije** [comment]
I can't test it on staging. somehow this branch isn't building. @noelheesen can you check this code and test it tomorrow?

**Comment by noelheesen** [comment]
I will look into this when I'm finished with the chat notification @nicolasmarabel @ralphboeije . As for the staging it might has something to do with my wrongdoing earlier, maybe @Krijger  or @wouterd can look into this?

**Comment by noelheesen** [comment]
@nicolasmarabel , @ralphboeije Only branches with the prefix 'fix' or 'feat' will be built on staging. I'll test and review the branch locally today.

**Comment by ralphboeije** [comment]
@noelheesen thanks for the check. Do you think it is needed to rename the branch, or can we merge this as is?

**Comment by nicolasmarabel** [comment]
@ralphboeije @noelheesen 
Sorry guys if I did it in the wrong prefix branch, I can change this and do it in other branch with the correct prefix.

**Comment by noelheesen** [comment]
@nicolasmarabel It's no problem, happened to me too. I'd say we can just merge this with develop. The only thing that's left to do is the dutch translation for the key @ralphboeije

**Comment by nicolasmarabel** [comment]
@noelheesen Ok, thanks! @ralphboeije if you give me the dutch translation for the key I can add it

**Comment by ralphboeije** [comment]
@nicolasmarabel I will do that in phraseapp with a seperate copy PR to Github

**Pull request merged**
